name: softify
description: "An ad-free, paywall-free mobile music streaming application."
publish_to: 'none'

version: 1.0.1+2

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  just_audio: ^0.9.36
  audio_service: ^0.18.14
  youtube_explode_dart: ^3.1.0
  background_downloader: ^8.5.2
  drift: ^2.16.0
  sqlite3_flutter_libs: ^0.5.20
  path_provider: ^2.1.2
  path: ^1.9.0
  http: ^1.2.0
  audio_session: ^0.1.18
  rxdart: ^0.27.7
  crypto: ^3.0.3
  dart_des: ^1.0.2
  palette_generator: ^0.3.3+7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  drift_dev: ^2.16.0
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
  assets:
    - assets/logo/
